export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Quiz } from './Quiz'
export { default as Stats } from './Stats'
export { default as History } from './History'
export { default as Leaderboard } from './Leaderboard'
